package com.varun.ignyt.auth

import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.GetCredentialInterruptedException
import androidx.credentials.exceptions.GetCredentialProviderConfigurationException
import androidx.credentials.exceptions.NoCredentialException
import com.getcapacitor.JSObject
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withTimeout

/**
 * Capacitor bridge for the IGNYT account layer: Google Sign-In (via androidx Credential
 * Manager, the current non-deprecated API) exchanged for a Firebase Authentication session.
 * Firebase Auth persists the session itself and restores it offline, so getCurrentUser()
 * works with no network after a previous successful sign-in.
 *
 * Same contract as HealthConnectPlugin: every method resolves {"success": true, "data": ...}
 * or {"success": false, "error": "..."} -- never rejects, and never crashes the app. All
 * Firebase access is lazy and null-checked so a missing/invalid google-services.json (the
 * repo does not ship one; it must come from the user's Firebase Console) degrades to a clean
 * "not configured" error instead of an app-wide IllegalStateException at startup.
 *
 * The Google ID token is exchanged for the Firebase session and immediately discarded --
 * it is never logged, never stored, and never returned across the JS bridge.
 */
@CapacitorPlugin(name = "IgnytAuth")
class AuthPlugin : com.getcapacitor.Plugin() {

    // SupervisorJob + handler for the same reason as HealthConnectPlugin: one failing
    // launch{} must never cancel the scope or reach the default handler and crash the app.
    private val pluginScope = CoroutineScope(
        SupervisorJob() + Dispatchers.Main + CoroutineExceptionHandler { _, e ->
            Log.e("IgnytAuth", "Unhandled coroutine exception in AuthPlugin", e)
        }
    )

    override fun handleOnDestroy() {
        pluginScope.cancel()
    }

    /** Null when google-services.json wasn't present at build time (FirebaseInitProvider
     *  then has nothing to initialize) or Firebase itself failed to init. */
    private fun firebaseAuthOrNull(): FirebaseAuth? = try {
        if (FirebaseApp.getApps(context).isEmpty()) null else FirebaseAuth.getInstance()
    } catch (e: Exception) {
        Log.w("IgnytAuth", "Firebase not available: ${e.message}")
        null
    }

    /** The OAuth web client id is a resource generated by the google-services gradle plugin
     *  from google-services.json. Looked up dynamically (not R.string.default_web_client_id)
     *  so this file still compiles when the config file isn't in the repo yet. */
    private fun webClientIdOrNull(): String? {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (resId != 0) context.getString(resId).takeIf { it.isNotBlank() } else null
    }

    private fun userJson(user: FirebaseUser): JSObject = JSObject().apply {
        put("uid", user.uid)
        put("displayName", user.displayName ?: "")
        put("email", user.email ?: "")
        put("photoUrl", user.photoUrl?.toString() ?: "")
    }

    /** Reports whether sign-in can work at all on this build/device, without side effects. */
    @PluginMethod
    fun isConfigured(call: PluginCall) {
        try {
            val configured = firebaseAuthOrNull() != null && webClientIdOrNull() != null
            resolveSuccess(call, JSObject().apply { put("configured", configured) })
        } catch (e: Exception) {
            resolveError(call, "isConfigured failed: ${e.message}")
        }
    }

    /** Restores the persisted Firebase session. Works fully offline -- Firebase Auth caches
     *  the signed-in user on disk and only refreshes tokens opportunistically. */
    @PluginMethod
    fun getCurrentUser(call: PluginCall) {
        try {
            val auth = firebaseAuthOrNull()
            if (auth == null) {
                resolveSuccess(call, JSObject().apply { put("signedIn", false); put("configured", false) })
                return
            }
            val user = auth.currentUser
            resolveSuccess(call, JSObject().apply {
                put("configured", true)
                put("signedIn", user != null)
                if (user != null) put("user", userJson(user))
            })
        } catch (e: Exception) {
            resolveError(call, "getCurrentUser failed: ${e.message}")
        }
    }

    @PluginMethod
    fun signIn(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        val webClientId = webClientIdOrNull()
        if (auth == null || webClientId == null) {
            resolveError(call, "Sign-in isn't configured in this build yet (missing Firebase configuration).")
            return
        }
        val currentActivity = activity
        if (currentActivity == null) {
            resolveError(call, "Sign-in requires a foreground activity.")
            return
        }
        pluginScope.launch {
            try {
                // filterByAuthorizedAccounts=false: show every Google account on the device,
                // not only ones that already authorized IGNYT -- this is a first sign-in flow.
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(webClientId)
                    .setAutoSelectEnabled(false)
                    .build()
                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()

                // No artificial timeout here: this shows system UI and legitimately waits on
                // the user. Cancellation/dismissal arrives as GetCredentialCancellationException.
                val credentialManager = CredentialManager.create(currentActivity)
                val result = credentialManager.getCredential(currentActivity, request)

                val credential = result.credential
                if (credential !is CustomCredential ||
                    credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                ) {
                    resolveError(call, "Google returned an unexpected credential type.")
                    return@launch
                }
                val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken

                // The token-for-session exchange IS a plain network call, so this one gets a
                // real timeout -- a hung request must not leave the button spinning forever.
                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = withTimeout(30_000L) {
                    auth.signInWithCredential(firebaseCredential).await()
                }
                val user = authResult.user
                if (user == null) {
                    resolveError(call, "Sign-in completed but no user was returned. Please try again.")
                    return@launch
                }
                resolveSuccess(call, JSObject().apply {
                    put("signedIn", true)
                    put("user", userJson(user))
                })
            } catch (e: GetCredentialCancellationException) {
                resolveError(call, "Sign-in was cancelled.")
            } catch (e: NoCredentialException) {
                resolveError(call, "No Google account is available on this device. Add a Google account in Android Settings first.")
            } catch (e: GetCredentialProviderConfigurationException) {
                resolveError(call, "Google Play Services isn't available or is out of date on this device.")
            } catch (e: GetCredentialInterruptedException) {
                resolveError(call, "Sign-in was interrupted. Please try again.")
            } catch (e: GetCredentialException) {
                resolveError(call, "Google Sign-In failed: ${e.message ?: e.type}")
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Sign-in timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                // Firebase network failures land here (FirebaseNetworkException etc.).
                resolveError(call, "Sign-in failed: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun signOut(call: PluginCall) {
        pluginScope.launch {
            try {
                firebaseAuthOrNull()?.signOut()
            } catch (e: Exception) {
                Log.w("IgnytAuth", "Firebase signOut failed: ${e.message}")
            }
            try {
                // Clears the credential-manager session so the next sign-in shows the account
                // picker again instead of silently reusing the last account.
                CredentialManager.create(context).clearCredentialState(ClearCredentialStateRequest())
            } catch (e: Exception) {
                // Non-fatal: the Firebase session is already gone, which is what "signed out"
                // means for the app. Worst case the account picker preselects the old account.
                Log.w("IgnytAuth", "clearCredentialState failed: ${e.message}")
            }
            resolveSuccess(call, JSObject().apply { put("signedOut", true) })
        }
    }

    private fun resolveSuccess(call: PluginCall, data: JSObject) {
        call.resolve(JSObject().apply { put("success", true); put("data", data) })
    }

    private fun resolveError(call: PluginCall, message: String) {
        call.resolve(JSObject().apply { put("success", false); put("error", message) })
    }
}
