package com.varun.ignyt.auth

import android.content.pm.PackageManager
import android.os.Build
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.GetCredentialInterruptedException
import androidx.credentials.exceptions.GetCredentialProviderConfigurationException
import androidx.credentials.exceptions.NoCredentialException
import com.getcapacitor.JSObject
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthException
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.PhoneAuthCredential
import com.google.firebase.auth.PhoneAuthOptions
import com.google.firebase.auth.PhoneAuthProvider
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicBoolean
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withTimeout

/**
 * Capacitor bridge for the IGNYT account layer: Google Sign-In (via androidx Credential
 * Manager, the current non-deprecated API) exchanged for a Firebase Authentication session.
 * Firebase Auth persists the session itself and restores it offline, so getCurrentUser()
 * works with no network after a previous successful sign-in.
 *
 * Same contract as HealthConnectPlugin: every method resolves {"success": true, "data": ...}
 * or {"success": false, "error": "..."} -- never rejects, and never crashes the app. All
 * Firebase access is lazy and null-checked so a missing/invalid google-services.json (the
 * repo does not ship one; it must come from the user's Firebase Console) degrades to a clean
 * "not configured" error instead of an app-wide IllegalStateException at startup.
 *
 * The Google ID token is exchanged for the Firebase session and immediately discarded --
 * it is never logged, never stored, and never returned across the JS bridge.
 */
@CapacitorPlugin(name = "IgnytAuth")
class AuthPlugin : com.getcapacitor.Plugin() {

    // SupervisorJob + handler for the same reason as HealthConnectPlugin: one failing
    // launch{} must never cancel the scope or reach the default handler and crash the app.
    private val pluginScope = CoroutineScope(
        SupervisorJob() + Dispatchers.Main + CoroutineExceptionHandler { _, e ->
            Log.e("IgnytAuth", "Unhandled coroutine exception in AuthPlugin", e)
        }
    )

    override fun handleOnDestroy() {
        pluginScope.cancel()
    }

    /** Null when google-services.json wasn't present at build time (FirebaseInitProvider
     *  then has nothing to initialize) or Firebase itself failed to init. */
    private fun firebaseAuthOrNull(): FirebaseAuth? = try {
        if (FirebaseApp.getApps(context).isEmpty()) null else FirebaseAuth.getInstance()
    } catch (e: Exception) {
        Log.w("IgnytAuth", "Firebase not available: ${e.message}")
        null
    }

    /** The OAuth web client id is a resource generated by the google-services gradle plugin
     *  from google-services.json. Looked up dynamically (not R.string.default_web_client_id)
     *  so this file still compiles when the config file isn't in the repo yet. */
    private fun webClientIdOrNull(): String? {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (resId != 0) context.getString(resId).takeIf { it.isNotBlank() } else null
    }

    private fun userJson(user: FirebaseUser): JSObject = JSObject().apply {
        put("uid", user.uid)
        put("displayName", user.displayName ?: "")
        put("email", user.email ?: "")
        put("photoUrl", user.photoUrl?.toString() ?: "")
        put("emailVerified", user.isEmailVerified)
        put("phoneNumber", user.phoneNumber ?: "")
        put("provider", when {
            user.providerData.any { it.providerId == "google.com" } -> "google"
            user.providerData.any { it.providerId == "phone" } -> "phone"
            else -> "password"
        })
    }

    /** Maps Firebase Auth's error codes to short, user-facing text. Falls back to the raw
     *  message for codes not worth a bespoke string. Never exposes stack traces or internal
     *  detail to the JS layer. */
    private fun authErrorMessage(e: FirebaseAuthException): String = when (e.errorCode) {
        "ERROR_INVALID_EMAIL" -> "That doesn't look like a valid email address."
        "ERROR_EMAIL_ALREADY_IN_USE" -> "An account already exists for this email. Try signing in instead."
        "ERROR_WEAK_PASSWORD" -> "Password is too weak — use at least 6 characters."
        "ERROR_WRONG_PASSWORD", "ERROR_INVALID_CREDENTIAL" -> "Incorrect email or password."
        "ERROR_USER_NOT_FOUND" -> "No account found for this email."
        "ERROR_USER_DISABLED" -> "This account has been disabled."
        "ERROR_TOO_MANY_REQUESTS" -> "Too many attempts. Please wait a moment and try again."
        "ERROR_NETWORK_REQUEST_FAILED" -> "Network error. Check your connection and try again."
        else -> e.message ?: "Something went wrong. Please try again."
    }

    /* =====================================================================
       SIGNING FINGERPRINTS

       Firebase phone auth verifies the app through Play Integrity, which is keyed to the
       signing certificate. If the certificate's fingerprints are not registered on the Firebase
       project, verification fails — and it fails with a generic message that says nothing about
       fingerprints, which is why this is such a common time sink.

       SHA-1 alone is not enough. google-services.json only ever carries SHA-1 (the
       certificate_hash field), so that file cannot tell anyone whether SHA-256 is registered;
       only the Firebase Console shows it. Play Integrity requires SHA-256. Rather than leave
       the user guessing, the app computes its OWN certificate fingerprints at runtime and can
       report them for comparison against the Console.

       These are public values — a certificate fingerprint is derived from the public
       certificate shipped inside every copy of the APK. Nothing secret is exposed.
    ===================================================================== */

    private fun fingerprints(): Pair<String, String>? = try {
        val pm = context.packageManager
        val certBytes: ByteArray? = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            val info = pm.getPackageInfo(context.packageName, PackageManager.GET_SIGNING_CERTIFICATES)
            info.signingInfo?.apkContentsSigners?.firstOrNull()?.toByteArray()
        } else {
            @Suppress("DEPRECATION")
            val info = pm.getPackageInfo(context.packageName, PackageManager.GET_SIGNATURES)
            @Suppress("DEPRECATION")
            info.signatures?.firstOrNull()?.toByteArray()
        }
        if (certBytes == null) null else {
            fun digest(algorithm: String) = java.security.MessageDigest.getInstance(algorithm)
                .digest(certBytes)
                .joinToString(":") { "%02X".format(it) }
            Pair(digest("SHA-1"), digest("SHA-256"))
        }
    } catch (e: Exception) {
        Log.w("IgnytAuth", "Could not read signing certificate: ${e.message}")
        null
    }

    /**
     * Reports the running app's certificate fingerprints so they can be checked against the
     * Firebase Console. Returns both, plus a flag for whether Firebase is initialised at all.
     * Safe to call any time; performs no network I/O and changes no state.
     */
    @PluginMethod
    fun checkSigning(call: PluginCall) {
        try {
            val fp = fingerprints()
            val auth = firebaseAuthOrNull()
            resolveSuccess(call, JSObject().apply {
                put("packageName", context.packageName)
                put("firebaseInitialised", auth != null)
                put("sha1", fp?.first ?: "")
                put("sha256", fp?.second ?: "")
                put("readable", fp != null)
            })
        } catch (e: Exception) {
            resolveError(call, "Could not read signing information: ${e.message}")
        }
    }

    /** Reports whether sign-in can work at all on this build/device, without side effects. */
    @PluginMethod
    fun isConfigured(call: PluginCall) {
        try {
            val configured = firebaseAuthOrNull() != null && webClientIdOrNull() != null
            resolveSuccess(call, JSObject().apply { put("configured", configured) })
        } catch (e: Exception) {
            resolveError(call, "isConfigured failed: ${e.message}")
        }
    }

    /** Restores the persisted Firebase session. Works fully offline -- Firebase Auth caches
     *  the signed-in user on disk and only refreshes tokens opportunistically. */
    @PluginMethod
    fun getCurrentUser(call: PluginCall) {
        try {
            val auth = firebaseAuthOrNull()
            if (auth == null) {
                resolveSuccess(call, JSObject().apply { put("signedIn", false); put("configured", false) })
                return
            }
            val user = auth.currentUser
            resolveSuccess(call, JSObject().apply {
                put("configured", true)
                put("signedIn", user != null)
                if (user != null) put("user", userJson(user))
            })
        } catch (e: Exception) {
            resolveError(call, "getCurrentUser failed: ${e.message}")
        }
    }

    /**
     * Returns a short-lived Firebase ID token (JWT) for the currently signed-in user, for
     * authenticating requests to the IGNYT Integration Service backend. The backend verifies
     * this token with the Firebase Admin SDK, so it can trust the uid without the client ever
     * asserting one.
     *
     * Security: this returns ONLY the short-lived ID token (default ~1h expiry), minted on
     * demand. No long-lived secret (refresh token, credential) is ever exposed to JS. The
     * token is never logged. `forceRefresh` is accepted so the JS layer can retry once with a
     * fresh token after a 401 without a full re-auth.
     */
    @PluginMethod
    fun getIdToken(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build (missing Firebase configuration).")
            return
        }
        val user = auth.currentUser
        if (user == null) {
            resolveSuccess(call, JSObject().apply { put("signedIn", false) })
            return
        }
        val forceRefresh = call.getBoolean("forceRefresh", false) ?: false
        pluginScope.launch {
            try {
                // Plain network call when a refresh is needed -> bounded timeout so a hung
                // request never leaves the caller waiting forever. Cached token returns instantly.
                val result = withTimeout(30_000L) { user.getIdToken(forceRefresh).await() }
                val token = result?.token
                if (token.isNullOrBlank()) {
                    resolveError(call, "Could not obtain an ID token. Please sign in again.")
                    return@launch
                }
                resolveSuccess(call, JSObject().apply {
                    put("signedIn", true)
                    put("uid", user.uid)
                    put("token", token)
                })
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Fetching sign-in token timed out. Check your connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Could not obtain an ID token: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun signIn(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        val webClientId = webClientIdOrNull()
        if (auth == null || webClientId == null) {
            resolveError(call, "Sign-in isn't configured in this build yet (missing Firebase configuration).")
            return
        }
        val currentActivity = activity
        if (currentActivity == null) {
            resolveError(call, "Sign-in requires a foreground activity.")
            return
        }
        pluginScope.launch {
            try {
                // filterByAuthorizedAccounts=false: show every Google account on the device,
                // not only ones that already authorized IGNYT -- this is a first sign-in flow.
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(webClientId)
                    .setAutoSelectEnabled(false)
                    .build()
                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()

                // No artificial timeout here: this shows system UI and legitimately waits on
                // the user. Cancellation/dismissal arrives as GetCredentialCancellationException.
                val credentialManager = CredentialManager.create(currentActivity)
                val result = credentialManager.getCredential(currentActivity, request)

                val credential = result.credential
                if (credential !is CustomCredential ||
                    credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                ) {
                    resolveError(call, "Google returned an unexpected credential type.")
                    return@launch
                }
                val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken

                // The token-for-session exchange IS a plain network call, so this one gets a
                // real timeout -- a hung request must not leave the button spinning forever.
                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult = withTimeout(30_000L) {
                    auth.signInWithCredential(firebaseCredential).await()
                }
                val user = authResult.user
                if (user == null) {
                    resolveError(call, "Sign-in completed but no user was returned. Please try again.")
                    return@launch
                }
                resolveSuccess(call, JSObject().apply {
                    put("signedIn", true)
                    put("user", userJson(user))
                })
            } catch (e: GetCredentialCancellationException) {
                resolveError(call, "Sign-in was cancelled.")
            } catch (e: NoCredentialException) {
                resolveError(call, "No Google account is available on this device. Add a Google account in Android Settings first.")
            } catch (e: GetCredentialProviderConfigurationException) {
                resolveError(call, "Google Play Services isn't available or is out of date on this device.")
            } catch (e: GetCredentialInterruptedException) {
                resolveError(call, "Sign-in was interrupted. Please try again.")
            } catch (e: GetCredentialException) {
                resolveError(call, "Google Sign-In failed: ${e.message ?: e.type}")
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Sign-in timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                // Firebase network failures land here (FirebaseNetworkException etc.).
                resolveError(call, "Sign-in failed: ${e.message ?: "unknown error"}")
            }
        }
    }

    /* =====================================================================
       PHONE / SMS AUTHENTICATION

       Firebase's phone flow is callback-based, not Task-based, and it has a trap: on a device
       where Play Integrity auto-retrieval works, onVerificationCompleted can fire BEFORE (or
       instead of) onCodeSent, and onCodeAutoRetrievalTimeOut fires afterwards regardless. A
       PluginCall may only be resolved once, so every path goes through `settled` -- resolving
       twice is what turns a working sign-in into a permanently spinning button.

       Auto-completion is deliberately NOT signed in from inside sendOtp. It reports
       autoVerified=true and stashes the credential; JS then calls verifyOtp, which consumes
       it. That keeps "who navigates, and when" in one place in the JS layer instead of
       splitting it across two callbacks that fire in a device-dependent order.
    ===================================================================== */

    /** Set by onVerificationCompleted when Android auto-reads the SMS. Consumed by verifyOtp. */
    private var autoCredential: PhoneAuthCredential? = null
    private var lastVerificationId: String? = null
    private var resendToken: PhoneAuthProvider.ForceResendingToken? = null

    @PluginMethod
    fun sendOtp(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build (missing Firebase configuration).")
            return
        }
        val currentActivity = activity
        if (currentActivity == null) {
            resolveError(call, "Phone sign-in requires a foreground activity.")
            return
        }
        val phone = call.getString("phoneNumber")?.trim().orEmpty()
        if (!phone.startsWith("+") || phone.length < 8) {
            resolveError(call, "Enter a valid phone number including the country code.")
            return
        }

        autoCredential = null
        val settled = AtomicBoolean(false)

        val callbacks = object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
            override fun onVerificationCompleted(credential: PhoneAuthCredential) {
                Log.d("IgnytAuth", "phone: onVerificationCompleted (auto-retrieved)")
                autoCredential = credential
                // smsCode is non-null when Android actually read the message, which lets the
                // JS layer pre-fill the boxes so the user sees what is happening.
                if (settled.compareAndSet(false, true)) {
                    resolveSuccess(call, JSObject().apply {
                        put("autoVerified", true)
                        put("verificationId", lastVerificationId ?: "")
                        put("smsCode", credential.smsCode ?: "")
                    })
                }
            }

            override fun onVerificationFailed(e: com.google.firebase.FirebaseException) {
                Log.w("IgnytAuth", "phone: onVerificationFailed: ${e.message}")
                if (settled.compareAndSet(false, true)) resolveError(call, phoneErrorMessage(e))
            }

            override fun onCodeSent(id: String, token: PhoneAuthProvider.ForceResendingToken) {
                Log.d("IgnytAuth", "phone: onCodeSent")
                lastVerificationId = id
                resendToken = token
                if (settled.compareAndSet(false, true)) {
                    resolveSuccess(call, JSObject().apply {
                        put("autoVerified", false)
                        put("verificationId", id)
                        put("codeSent", true)
                    })
                }
            }

            override fun onCodeAutoRetrievalTimeOut(id: String) {
                // Normal end of the auto-retrieval window, not an error. Only matters if
                // nothing else resolved first, which would mean the SMS never arrived.
                Log.d("IgnytAuth", "phone: auto-retrieval timed out")
                lastVerificationId = id
                if (settled.compareAndSet(false, true)) {
                    resolveSuccess(call, JSObject().apply {
                        put("autoVerified", false)
                        put("verificationId", id)
                        put("codeSent", true)
                    })
                }
            }
        }

        try {
            val builder = PhoneAuthOptions.newBuilder(auth)
                .setPhoneNumber(phone)
                .setTimeout(60L, TimeUnit.SECONDS)
                .setActivity(currentActivity)
                .setCallbacks(callbacks)
            // Resend reuses the token so Firebase treats it as a resend rather than a fresh
            // request, which is what keeps it from tripping the abuse throttle.
            if (call.getBoolean("resend", false) == true) {
                resendToken?.let { builder.setForceResendingToken(it) }
            }
            PhoneAuthProvider.verifyPhoneNumber(builder.build())

            /* Watchdog. Every normal outcome arrives as one of the four callbacks above, but
               there is one path where NONE of them fire: app verification fails, Firebase
               opens its reCAPTCHA page in a browser, and the user backs out of it. The
               PluginCall would then never resolve and the JS button would spin forever — the
               exact "stuck on Signing in" failure this plugin was written to eliminate.

               setTimeout() is 60s, so 90s is comfortably past every legitimate outcome. */
            pluginScope.launch {
                kotlinx.coroutines.delay(90_000L)
                if (settled.compareAndSet(false, true)) {
                    Log.w("IgnytAuth", "phone: no callback within 90s - app verification likely fell back to the web flow")
                    resolveError(call,
                        "Verification didn't complete. If a browser page opened, this build " +
                        "isn't passing Play Integrity — check that its SHA-256 is registered in " +
                        "Firebase and that the Play Integrity API is enabled for the project.")
                }
            }
        } catch (e: Exception) {
            Log.e("IgnytAuth", "phone: verifyPhoneNumber threw", e)
            if (settled.compareAndSet(false, true)) {
                resolveError(call, "Could not start phone verification: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun verifyOtp(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build (missing Firebase configuration).")
            return
        }
        val code = call.getString("code")?.trim().orEmpty()
        val verificationId = call.getString("verificationId")?.takeIf { it.isNotBlank() } ?: lastVerificationId

        // An auto-retrieved credential is already complete and is preferred over rebuilding one
        // from a typed code -- it is the same SMS either way, and this path cannot mistype it.
        val credential: PhoneAuthCredential = autoCredential ?: run {
            if (verificationId.isNullOrBlank()) {
                resolveError(call, "That code has expired. Request a new one.")
                return
            }
            if (code.length < 6) {
                resolveError(call, "Enter the 6-digit code from the SMS.")
                return
            }
            PhoneAuthProvider.getCredential(verificationId, code)
        }

        pluginScope.launch {
            try {
                val authResult = withTimeout(30_000L) { auth.signInWithCredential(credential).await() }
                val user = authResult.user
                if (user == null) {
                    resolveError(call, "Sign-in completed but no user was returned. Please try again.")
                    return@launch
                }
                Log.d("IgnytAuth", "phone: signInWithCredential OK, uid=${user.uid}")
                // Single-use: a stale credential must not silently sign in the next attempt.
                autoCredential = null
                lastVerificationId = null
                resolveSuccess(call, JSObject().apply {
                    put("signedIn", true)
                    put("isNewUser", authResult.additionalUserInfo?.isNewUser ?: false)
                    put("user", userJson(user))
                })
            } catch (e: FirebaseAuthException) {
                autoCredential = null
                /* "Wrong code" and "code expired" need different UI: a typo should leave the
                   user on the code field to correct it, while an expired session must send
                   them back to request a new SMS. Firebase distinguishes them by error code,
                   so report that distinction as a flag -- the JS layer must never have to
                   pattern-match English prose to decide where to navigate. */
                val expired = e.errorCode == "ERROR_SESSION_EXPIRED"
                if (expired) lastVerificationId = null
                resolveOtpError(
                    call,
                    when {
                        expired -> "That code has expired. Request a new one."
                        e is FirebaseAuthInvalidCredentialsException ->
                            "That code isn't right. Check it and try again."
                        else -> authErrorMessage(e)
                    },
                    expired
                )
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Verifying the code timed out. Check your connection and try again.")
            } catch (e: Exception) {
                autoCredential = null
                resolveError(call, "Could not verify the code: ${e.message ?: "unknown error"}")
            }
        }
    }

    /** Phone verification fails through FirebaseException, not only FirebaseAuthException, so
     *  this matches on the message when there is no error code to read. */
    private fun phoneErrorMessage(e: com.google.firebase.FirebaseException): String {
        if (e is FirebaseAuthException) return authErrorMessage(e)
        val m = e.message ?: return "Could not send the code. Please try again."
        return when {
            m.contains("BILLING_NOT_ENABLED", true) ->
                "Phone sign-in needs billing enabled on the Firebase project (Blaze plan)."
            m.contains("quota", true) || m.contains("TOO_MANY", true) ->
                "The SMS quota for this project has been used up. Try again later."
            m.contains("invalid", true) && m.contains("phone", true) ->
                "That phone number isn't valid. Include the country code."
            m.contains("reCAPTCHA", true) || m.contains("captcha", true) ->
                /* Reaching reCAPTCHA at all means Play Integrity verification failed — the
                   fallback is the symptom, not the cause, so the message names the cause. */
                "This build could not be verified with Play Integrity, so Firebase fell back to " +
                "a web check. Register its SHA-256 in the Firebase Console and enable the Play " +
                "Integrity API for the project."
            m.contains("app-not-authorized", true) || m.contains("APP_NOT_VERIFIED", true) ||
            m.contains("MISSING_CLIENT_IDENTIFIER", true) -> {
                /* The single most common cause, and the one Firebase's own message never names.
                   Print the fingerprint the project is actually missing rather than telling the
                   user to go and find it — SHA-256 in particular is not in google-services.json,
                   so there is nowhere on disk they could have looked it up. */
                val sha256 = fingerprints()?.second
                Log.w("IgnytAuth", "Phone auth rejected this build. SHA-256=$sha256")
                if (sha256 != null)
                    "This build isn't authorized for phone sign-in. Add this SHA-256 fingerprint " +
                    "to the Firebase Console (Project settings ▸ Your apps ▸ ${context.packageName}):\n$sha256"
                else
                    "This build isn't authorized for phone sign-in. Add its SHA-1 and SHA-256 " +
                    "fingerprints in the Firebase Console."
            }
            m.contains("network", true) ->
                "Network error. Check your connection and try again."
            else -> m
        }
    }

    @PluginMethod
    fun signUpWithEmail(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build yet (missing Firebase configuration).")
            return
        }
        val email = call.getString("email")?.trim() ?: ""
        val password = call.getString("password") ?: ""
        if (email.isEmpty() || password.isEmpty()) {
            resolveError(call, "Enter an email and password.")
            return
        }
        pluginScope.launch {
            try {
                val authResult = withTimeout(30_000L) { auth.createUserWithEmailAndPassword(email, password).await() }
                val user = authResult.user
                if (user == null) {
                    resolveError(call, "Account creation completed but no user was returned. Please try again.")
                    return@launch
                }
                // Best-effort: a signup should still succeed locally even if the verification
                // email fails to send (e.g. transient network blip right after account creation).
                try { withTimeout(15_000L) { user.sendEmailVerification().await() } } catch (e: Exception) {
                    Log.w("IgnytAuth", "sendEmailVerification after signup failed: ${e.message}")
                }
                resolveSuccess(call, JSObject().apply { put("signedIn", true); put("user", userJson(user)) })
            } catch (e: FirebaseAuthException) {
                resolveError(call, authErrorMessage(e))
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Sign-up timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Sign-up failed: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun signInWithEmail(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build yet (missing Firebase configuration).")
            return
        }
        val email = call.getString("email")?.trim() ?: ""
        val password = call.getString("password") ?: ""
        if (email.isEmpty() || password.isEmpty()) {
            resolveError(call, "Enter an email and password.")
            return
        }
        pluginScope.launch {
            try {
                val authResult = withTimeout(30_000L) { auth.signInWithEmailAndPassword(email, password).await() }
                val user = authResult.user
                if (user == null) {
                    resolveError(call, "Sign-in completed but no user was returned. Please try again.")
                    return@launch
                }
                resolveSuccess(call, JSObject().apply { put("signedIn", true); put("user", userJson(user)) })
            } catch (e: FirebaseAuthException) {
                resolveError(call, authErrorMessage(e))
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Sign-in timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Sign-in failed: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun sendPasswordReset(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        if (auth == null) {
            resolveError(call, "Sign-in isn't configured in this build yet (missing Firebase configuration).")
            return
        }
        val email = call.getString("email")?.trim() ?: ""
        if (email.isEmpty()) {
            resolveError(call, "Enter your email address.")
            return
        }
        pluginScope.launch {
            try {
                withTimeout(30_000L) { auth.sendPasswordResetEmail(email).await() }
                resolveSuccess(call, JSObject().apply { put("sent", true) })
            } catch (e: FirebaseAuthException) {
                resolveError(call, authErrorMessage(e))
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Request timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Could not send reset email: ${e.message ?: "unknown error"}")
            }
        }
    }

    /** Resends the verification email to the currently signed-in user. */
    @PluginMethod
    fun sendEmailVerification(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        val user = auth?.currentUser
        if (user == null) {
            resolveError(call, "You need to be signed in to verify your email.")
            return
        }
        pluginScope.launch {
            try {
                withTimeout(15_000L) { user.sendEmailVerification().await() }
                resolveSuccess(call, JSObject().apply { put("sent", true) })
            } catch (e: FirebaseAuthException) {
                resolveError(call, authErrorMessage(e))
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Request timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Could not send verification email: ${e.message ?: "unknown error"}")
            }
        }
    }

    /** Network call to refresh the current user's data from Firebase (e.g. to pick up
     *  emailVerified turning true after the user taps the link in their inbox). Deliberately
     *  separate from getCurrentUser, which stays instant/offline-safe for the boot path. */
    @PluginMethod
    fun reloadUser(call: PluginCall) {
        val auth = firebaseAuthOrNull()
        val user = auth?.currentUser
        if (user == null) {
            resolveSuccess(call, JSObject().apply { put("signedIn", false) })
            return
        }
        pluginScope.launch {
            try {
                withTimeout(15_000L) { user.reload().await() }
                resolveSuccess(call, JSObject().apply { put("signedIn", true); put("user", userJson(user)) })
            } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
                resolveError(call, "Request timed out. Check your internet connection and try again.")
            } catch (e: Exception) {
                resolveError(call, "Could not refresh account status: ${e.message ?: "unknown error"}")
            }
        }
    }

    @PluginMethod
    fun signOut(call: PluginCall) {
        pluginScope.launch {
            try {
                firebaseAuthOrNull()?.signOut()
            } catch (e: Exception) {
                Log.w("IgnytAuth", "Firebase signOut failed: ${e.message}")
            }
            try {
                // Clears the credential-manager session so the next sign-in shows the account
                // picker again instead of silently reusing the last account.
                CredentialManager.create(context).clearCredentialState(ClearCredentialStateRequest())
            } catch (e: Exception) {
                // Non-fatal: the Firebase session is already gone, which is what "signed out"
                // means for the app. Worst case the account picker preselects the old account.
                Log.w("IgnytAuth", "clearCredentialState failed: ${e.message}")
            }
            resolveSuccess(call, JSObject().apply { put("signedOut", true) })
        }
    }

    private fun resolveSuccess(call: PluginCall, data: JSObject) {
        call.resolve(JSObject().apply { put("success", true); put("data", data) })
    }

    private fun resolveError(call: PluginCall, message: String) {
        call.resolve(JSObject().apply { put("success", false); put("error", message) })
    }

    /** As resolveError, plus the expired/not-expired distinction the OTP screen needs to decide
     *  whether to keep the user on the code field or send them back to request a new SMS. */
    private fun resolveOtpError(call: PluginCall, message: String, expired: Boolean) {
        call.resolve(JSObject().apply {
            put("success", false); put("error", message); put("expired", expired)
        })
    }
}
