# -*- coding: utf-8 -*-
"""Import exercise instruction posters into www/assets/exercise-posters and write the manifest.

    python tools/build-exercise-posters.py <source-folder>

Which posters to take is read from tools/exercise-posters.txt rather than inferred from the
folder, because the poster export and the action-shot export arrive in the same directory at
almost the same dimensions - 1536x1024 against 1500x1000 - and nothing in the file itself says
which is which. Guessing by size would silently promote an action shot to a poster.

Posters are encoded differently from photos and for a different reason. A photo is glanced at
in a 38px row, so 480px and 4:2:0 chroma are generous. A poster is read: it carries step text,
a muscle diagram and a sets/reps strip, so it keeps its full width up to 1080px and full chroma,
which is what stops the orange headings fringing against white. That costs about 15x per file,
which is affordable for a handful and would not be for 445.

Native aspect is preserved and recorded in the manifest. The How To tab reserves the box from
those numbers, so the card below does not jump as the poster loads, and a portrait poster is
shown whole instead of being centre-cropped to 4:3 - a crop that took 40-50% off the two
portrait ones and cut the calf raise off at the calves.
"""
import io, os, re, shutil, sys, json
from PIL import Image

LIST = "tools/exercise-posters.txt"
DST = "www/assets/exercise-posters"
MANIFEST = "www/js/workout/exercise-posters.js"
MAX_W = 1080
QUALITY = 85


def main(src):
    slugs = []
    with io.open(LIST, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if line:
                slugs.append(line)

    have = {}
    for f in os.listdir(src):
        if f.lower().endswith((".png", ".jpg", ".jpeg")):
            have.setdefault(os.path.splitext(f)[0], f)

    missing = [s for s in slugs if s not in have]
    if missing:
        print("REFUSING: %d listed posters are not in %s: %s"
              % (len(missing), src, ", ".join(missing)))
        print("Fix the slug in %s, or point at the folder that has them." % LIST)
        return 1

    if os.path.isdir(DST):
        shutil.rmtree(DST)
    os.makedirs(DST)

    sizes, total = {}, 0
    for s in slugs:
        with Image.open(os.path.join(src, have[s])) as im:
            im = im.convert("RGB")
            w, h = im.size
            if w > MAX_W:                      # never upscale: a 1024px poster stays 1024px
                im = im.resize((MAX_W, round(h * MAX_W / w)), Image.LANCZOS)
            out = os.path.join(DST, s + ".jpg")
            # subsampling=0 keeps full chroma. Poster headings are saturated orange on white,
            # which is exactly where 4:2:0 smears.
            im.save(out, "JPEG", quality=QUALITY, optimize=True, progressive=True, subsampling=0)
            sizes[s] = list(im.size)
        total += os.path.getsize(out)

    io.open(MANIFEST, "w", encoding="utf-8").write(
        "/* Exercises whose How To tab shows a full instruction poster, and each poster's\n"
        "   pixel size. Generated by tools/build-exercise-posters.py from\n"
        "   tools/exercise-posters.txt; regenerate rather than editing by hand.\n\n"
        "   The dimensions are here so the How To tab can reserve the right box before the\n"
        "   image arrives. Posters are not all one shape - these run from 3:2 to 2:3 - so a\n"
        "   single hardcoded aspect would letterbox some and crop others. */\n"
        "window.IGNYT_EXERCISE_POSTERS = "
        + json.dumps(sizes, separators=(",", ":"), sort_keys=True) + ";\n")

    print("posters  : %d" % len(slugs))
    print("payload  : %.2f MB (avg %.0f KB)" % (total / 1048576.0, total / len(slugs) / 1024.0))
    for s in slugs:
        print("   %-46s %sx%s" % (s, sizes[s][0], sizes[s][1]))
    print("manifest : %s" % MANIFEST)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
