# -*- coding: utf-8 -*-
"""Import exercise photos into www/assets/exercises and regenerate the manifest.

    python tools/build-exercise-images.py <source-folder>

The source folder holds one image per exercise, named as the exercise's slug — the same
slug exerciseImageSrc() builds in app.js. Anything the CSV does not name is ignored, and
anything the CSV names but the folder lacks simply has no photo: the app falls back to a
muscle-coloured icon badge, which is the normal case rather than an error.

Images are re-encoded, not copied. The supplied sets have been 1170x851 and 1500x1000, and
the app draws them at 44-92px in a list row and about 430px on the How To tab. Bundling the
originals would have added 25-375 MB to an APK to serve pixels nothing renders.
"""
import csv, io, os, re, shutil, sys, json
from PIL import Image

CSV = "tools/workout_names.csv"
DST = "www/assets/exercises"
MANIFEST = "www/js/workout/exercise-images.js"
TARGET_W = 480
QUALITY = 78


def slug(name):
    s = name.lower().replace("&", " and ")
    s = re.sub(r"[()']", "", s)
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def main(src):
    names = []
    with io.open(CSV, encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            n = (r.get("exercise_name") or "").strip()
            if n:
                names.append(n)

    have = {}
    for f in os.listdir(src):
        if f.lower().endswith((".png", ".jpg", ".jpeg")):
            have.setdefault(os.path.splitext(f)[0], f)

    # Refuse to shrink coverage by accident: replacing the folder with a set that is missing
    # images the app currently ships would silently drop them from every screen.
    if os.path.isdir(DST):
        # Counting only .jpg here made an exercise whose illustration is an ANIMATION look
        # like it had none, so the guard waved through deleting it.
        current = {os.path.splitext(f)[0] for f in os.listdir(DST)
                   if f.lower().endswith((".jpg", ".gif", ".webp", ".png"))}
        lost = sorted(current - set(have))
        if lost:
            print("REFUSING: %d exercises would lose their photo, e.g. %s"
                  % (len(lost), ", ".join(lost[:8])))
            print("Pass a superset, or delete www/assets/exercises first if this is deliberate.")
            return 1
        # Animations are carried across the rebuild rather than deleted with everything else:
        # this script only ever writes JPEGs, so it cannot put them back.
        keep = {f: io.open(os.path.join(DST, f), "rb").read()
                for f in os.listdir(DST) if f.lower().endswith((".gif", ".webp"))}
        shutil.rmtree(DST)
        os.makedirs(DST, exist_ok=True)
        for f, blob in keep.items():
            io.open(os.path.join(DST, f), "wb").write(blob)
    os.makedirs(DST, exist_ok=True)

    written = total = 0
    for n in names:
        s = slug(n)
        if s not in have:
            continue
        with Image.open(os.path.join(src, have[s])) as im:
            im = im.convert("RGB")
            w, h = im.size
            if w > TARGET_W:
                im = im.resize((TARGET_W, round(h * TARGET_W / w)), Image.LANCZOS)
            out = os.path.join(DST, s + ".jpg")
            im.save(out, "JPEG", quality=QUALITY, optimize=True, progressive=True)
        total += os.path.getsize(out)
        written += 1

    # The manifest value is the FORMAT, not just presence: 1 for a .jpg still -- which is what
    # every entry used to be, so none had to be rewritten -- and the extension string for
    # anything else. Writing {s: 1} unconditionally is what would have un-shipped the
    # animations on the next run of this script.
    entries = {}
    for f in sorted(os.listdir(DST)):
        stem, ext = os.path.splitext(f)
        ext = ext.lower().lstrip(".")
        if ext in ("jpg", "gif", "webp", "png"):
            entries[stem] = 1 if ext == "jpg" else ext
    animated = sorted(k for k, v in entries.items() if v in ("gif", "webp"))
    io.open(MANIFEST, "w", encoding="utf-8").write(
        "/* Which exercises have an illustration, and in what format. Generated by\n"
        "   tools/build-exercise-images.py; regenerate it whenever images are added or\n"
        "   removed. exerciseImageSrc() consults this so an exercise without one renders its\n"
        "   icon badge directly, instead of requesting a file that 404s.\n\n"
        "   The value is 1 for a .jpg still and the extension string for anything else, which\n"
        "   is how an animated demonstration sits beside the stills. */\n"
        "window.IGNYT_EXERCISE_IMAGES = "
        + json.dumps(entries, separators=(",", ":"), sort_keys=True) + ";\n")
    if animated:
        print("animated : %d (%s)" % (len(animated), ", ".join(animated)))

    print("images   : %d of %d exercises (%.0f%%)" % (written, len(names), 100.0 * written / len(names)))
    print("payload  : %.2f MB (avg %.0f KB)" % (total / 1048576, total / written / 1024))
    print("manifest : %s" % MANIFEST)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
